-- This contains the SQL scripts for the leaderboard

CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(150) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
CREATE TABLE model (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	model_name VARCHAR(150) NOT NULL,
	model_content VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE score (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	model_id INT UNSIGNED NOT NULL,
	score INT UNSIGNED NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (model_id) REFERENCES model(id) ON DELETE CASCADE
);
CREATE INDEX idx_model_name ON model(model_name);
CREATE INDEX idx_score ON score(model_id);
